config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'static_pages#top'
  get "privacy_policy",to: 'static_pages#privacy_policy'
  get "disclaimer",to: 'static_pages#disclaimer'

  resources :records do
    resources :comment_records
    collection do
      get 'search'
    end
  end

  resources :rules do
    resources :comment_rules
    collection do
      get 'search'
    end
  end

  resources :users, only: [:edit, :update, :show,] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers' 
    get "index_records" => 'users#index_records'
    get "index_rules" => 'users#index_rules'
  end

  post 'like_record/:id' => 'like_records#create', as: 'create_like_record'
  delete 'like_record/:id' => 'like_records#destroy', as: 'destroy_like_record'
  post 'like_rule/:id' => 'like_rules#create', as: 'create_like_rule'
  delete 'like_rule/:id' => 'like_rules#destroy', as: 'destroy_like_rule'

  resources :relationships, only: [:create, :destroy]

  resources :advertisements, only: [:new, :create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
    @records = Record.limit(4).order("created_at DESC")
    @rules = Rule.limit(4).order("created_at DESC")
    @ad_2 = Advertisement.where(ad_rate_id: 2).order("RAND()").first
    @ad_5 = Advertisement.where(ad_rate_id: 5).order("RAND()").first
  end

  def privacy_policy
  end

  def disclaimer
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/disclaimer.html.erb
<% set_meta_tags title: "免責事項" %>
<div class="breadcrumbs">
  <% breadcrumb :disclaimer %>
</div>
<section class="content">
<h1><span>免責事項</span></h1>
<p>
FX Traders（以下、当サイト）に掲載している情報は、記載、記録、および情報の提供を目的としており、投資その他の行動を勧誘する目的で運営しているものではありません。また、当サイトに掲載されているFX会社の口座開設、利用登録は必ずお客様が納得された上で、お客様の責任のもと行ってください。<br>
登録したFX会社のFXトレードにおける損失等に関するお問い合わせには答えかねます。<br>
投資の最終決定は、お客様ご自身の判断でなさるようにお願いいたします。<br><br>

当サイトに掲載しているすべての記事、投稿、および情報やデータについて、その情報源の確実性を保証するものではありません。<br>
また、当サイトの提供情報を利用することで被った被害について、当方は一切の責任を負いません。<br>
万一、当サイトの提供情報の内容に誤りがあった場合においても当方は一切責任を負いません。<br><br>

当サイトが紹介しているFX会社のサービス情報につきましても、一部の原則固定型を除きスプレッドやスワップポイントの数値は日々変動しています。<br>
情報スペックならびに各種相場の影響を受ける値に関しては必ず各社のHP等に掲載されている最新の情報を確認の上、判断されるようお願いします。<br>
同時に当サイトは掲載情報の正確さを保証するものではありませんのであしからずご了承ください。<br><br>

尚、当サイトにおいて紹介しているFX会社並びにそのサービスやその他掲載情報は事前告知なしに修正、または削除する場合がございます。<br>
</p>
</section>
<div class="space"></div>

app/views/static_pages/privacy_policy.html.erb
<% set_meta_tags title: "プライバシーポリシー" %>
<div class="breadcrumbs">
  <% breadcrumb :privacy_policy %>
</div>
<section class="content">
<h1><span>プライバシーポリシー</span></h1>
<h3>個人情報保護方針</h3>
<p>
FX Traders（以下「当サイト」）は、個人情報に関する法令を遵守し、個人情報保護の重要性の認識と取組みを徹底し、個人情報の適切な取扱いと保護を推進致します。 <br>
当サイトをご利用頂く皆様の個人情報をお預かりするにあたり、以下のとおり個人情報保護方針を定め、個人情報保護の仕組みを構築します。<br><br>

<b>1.個人情報の取得、利用</b><br>
当サイトでは、メールでのお問い合わせの際に、名前（ハンドルネーム）、メールアドレス等の個人情報をご登録いただく場合がございます。 <br>
これらの個人情報は質問に対する回答や必要な情報を電子メールなどをでご連絡する場合に利用させていただくものであり、個人情報をご提供いただく際の目的以外では利用いたしません。<br><br>

<b>2.個人情報の管理</b><br>
当サイトは、皆様の個人情報を正確かつ最新の状態に保ち、個人情報への不正アクセス・紛失・破損・改ざん・漏洩などを防止するため、セキュリティシステムの維持・管理体制の整備等の必要な措置を講じ、安全対策を実施し個人情報の厳重な管理を行ないます。<br><br>

<b>3.個人情報の第三者への開示・提供の禁止</b><br>
当サイトは、皆様からお預かりした個人情報を適切に管理し、次のいずれかに該当する場合を除き、個人情報を第三者に開示いたしません。<br><br>

・本人の了解がある場合<br>
・法令等への協力のため、開示が必要となる場合<br><br>
</p>

<h3>Cookieの取り扱いについて</h3>
<p>
<b>1.Cookie</b><br>
Cookie(クッキー)とは、ホームページを訪問したユーザーの情報を一時的の保存する仕組み、またはそのデータです。ブラウザに一時的に保存されるものであり個人を特定するデータではありません。<br><br>

<b>2.Cookieの利用目的</b><br>
広告を配信しており、これに関連して、当該第三者の広告主が当サイトを訪問したユーザーのクッキー情報等を取得し、利用している場合があります。<br>
当該第三者によって取得されたクッキー情報等は、当該第三者のプライバシーポリシーに従って取り扱われます。<br><br>

また再訪問をしていただく為にも第三者の広告主が利用しております。<br><br>

本サイトではGoogleのタグマネージャー・Googleアナリティクス等からサイト内でのユーザーの行動データを集計し、お客様に役立つFXコンテンツ作りをする為、お客様におすすめできるFX会社を紹介する為に利用しております。<br><br>

Googleアナリティクス等、グーグルが行うデータ収集や処理の仕組みについては下記リンクをご覧ください。<br><br>

<a href="https://policies.google.com/technologies/partner-sites?hl=ja">Google のサービスを使用するサイトやアプリから収集した情報の Google による使用</a><br><br>

<a href="https://marketingplatform.google.com/about/analytics/terms/jp/">Google アナリティクス利用規約</a><br><br>

<b>3.Cookieの不許可設定</b><br>
ユーザーは、当該第三者のウェブサイト内に設けられたオプトアウトページにアクセスして、当該第三者によるクッキー情報等の広告配信への利用を停止する事ができます。<br><br>

お客様がブラウザの設定でクッキーの送受信を許可している場合、ウェブサイトはユーザーのブラウザからクッキーを取得できます。なお、お客様のブラウザはプライバシー保護の為、そのウェブサイトのサーバーが送受信したクッキーのみを送信します。<br>
お客様は、クッキーの送受信に関する設定を「すべてののクッキーを許可する」「全てのクッキーを拒否する」「クッキーを送受信したらユーザーに通知する」等から選択できます。<br><br>

設定方法はブラウザにより異なります。クッキーに関する設定方法は、お使いのブラウザの「ヘルプ」メニューでご確認下さい。<br>
すべてのクッキーを拒否する設定を選択されますと、認証が必要なサービスを受けられなくなる等インターネット上の各種サービスの利用上、制約を受ける場合がありますのでご注意下さい。<br><br>

<b>4.改定</b><br>
当サイトは、本「Cookieの取扱いについて」の全部または一部を改訂する事があります。重要な変更が行われた際にはサイト上にお知らせを表示する事もございます。<br>
</section>
<div class="space"></div>

app/views/static_pages/top.html.erb
<% set_meta_tags title: '取引ノートを作ろう！最高の取引教材はあなたの取引記録です！' %>
<section class="content">
  <h1><span>取引記録のノートを作ろう！</span></h1>
  <%= image_tag 'trading_note_.jpg', class: "top_img" %>
  <p class="catch">自分の取引記録が最高の取引教材になるその時まで</p>

  <h2 class="for_top">公開する取引ノートを作るメリット</h2>
  <ul>
    <li class="benefit">取引ルールが明確になる</li>
    <li class="benefit">取引ルールを守れるようになる</li>
    <li class="benefit">自身の取引に対する理解が深まる</li>
    <li class="benefit">取引ルールのブラッシュアップ</li>
    <li class="benefit">取引記録に対するフィードバック</li>
    <li class="benefit">他トレーダーの記録で勉強できる</li>
  </ul>
  <div class="space"></div>

  <h2 class="for_top">取引ノートで自身の取引を可視化！</h2>
  <p>自身の取引を記録することでデータを作りグラフ化していきます。</p>
  <p>自分の取引を客観的に見て取引精度をあげ、資産を増やしていきましょう！</p>
  <%= image_tag 'record_date.png', class: "top_img" %>
  <div class="space"></div>

  <h2 classs="for_top">みんなの取引記録をみてみよう！</h2>
    <div class="grid">
    <% @records.each do |record| %>
      <%= render partial: "shared/records", locals: { record: record } %>
    <% end %>
  </div>
  <%= link_to "もっと取引記録をみる", records_path, class: "btn_" %>
  <% unless user_signed_in? %>
    <div class="for_user">
      <div class="btn btn--white btn--radius">
        <%= link_to "新規登録して取引を記録する！", new_user_registration_path, class: "btn_word" %>
      </div>
      <div class="btn btn--white btn--radius">
        <%= link_to "ログインして取引を記録する！", new_user_session_path, class: "btn_word" %>
      </div>
    </div>
  <% end %>
  <div class="space"></div>

  <h2 class="for_top">みんなの取引手法をみてみよう！</h2>
  <div class="grid_ grid__res">
    <% @rules.each do |rule| %>
      <%= render partial: "shared/rules", locals: { rule: rule } %>
    <% end %>
  </div>
  <%= link_to "もっと取引手法をみる", rules_path, class: "btn_" %>
  <% unless user_signed_in? %>
    <div class="for_user">
      <div class="btn btn--white btn--radius">
        <%= link_to "新規登録して取引を記録する！", new_user_registration_path, class: "btn_word" %>
      </div>
      <div class="btn btn--white btn--radius">
        <%= link_to "ログインして取引を記録する！", new_user_session_path, class: "btn_word" %>
      </div>
    </div>
  <% end %>
  <div class="space">
  </div>
  <div class="ad_2_show"><%= link_to(image_tag(@ad_2.img_url), @ad_2.af_link)%></div>
  <div class="ad_5"><%= link_to(image_tag(@ad_5.img_url), @ad_5.af_link)%></div>
</section>