config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'static_pages#top'
  get "privacy_policy",to: 'static_pages#privacy_policy'
  get "disclaimer",to: 'static_pages#disclaimer'

  resources :records do
    resources :comment_records
    collection do
      get 'search'
    end
  end

  resources :rules do
    resources :comment_rules
    collection do
      get 'search'
    end
  end

  resources :users, only: [:edit, :update, :show,] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers' 
    get "index_records" => 'users#index_records'
    get "index_rules" => 'users#index_rules'
  end

  post 'like_record/:id' => 'like_records#create', as: 'create_like_record'
  delete 'like_record/:id' => 'like_records#destroy', as: 'destroy_like_record'
  post 'like_rule/:id' => 'like_rules#create', as: 'create_like_rule'
  delete 'like_rule/:id' => 'like_rules#destroy', as: 'destroy_like_rule'

  resources :relationships, only: [:create, :destroy]

  resources :advertisements, only: [:new, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, on: :create

  validates :name, presence: true

  has_many :records, dependent: :destroy
  has_many :rules, dependent: :destroy
  has_many :like_records
  has_many :like_rules

  def liked_by?(record_id)
    like_records.where(record_id: record_id).exists?
  end

  def liked__by?(rule_id)
    like_rules.where(rule_id: rule_id).exists?
  end

  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :show]
  before_action :set_user_id, except: [:edit, :update, :show]

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def show
    @name = @user.name
    @records = @user.records.order("created_at DESC").page(params[:page]).per(12)
    @rules = @user.rules.order("created_at DESC").page(params[:page]).per(8)
    @records_by_user = Record.where(user_id: @user.id)
    @pair_cat = @records_by_user.group(:pair_id).pluck(:pair_id)
    @all_pips = Record.where('pips not like?', '-%').pluck(:pips)
    @all_pips_ = Record.where('pips like?', '-%').pluck(:pips)
    @all_pf = @all_pips.sum/@all_pips_.sum.abs
    #直近1ヶ月
    @to = Date.current.at_end_of_day
    @from = @to - 1.month
    @records_by_user_month = Record.where(user_id: @user.id).where(created_at: @from...@to)
    @pair_cat_month = @records_by_user_month.group(:pair_id).pluck(:pair_id)
    @ad_5 = Advertisement.where(ad_rate_id: 5).order("RAND()").first
    @ad_5_ = Advertisement.where(ad_rate_id: 5).order("RAND()").second
    @ad_2 = Advertisement.where(ad_rate_id: 2).order("RAND()").first
    @ad_2_ = Advertisement.where(ad_rate_id: 2).order("RAND()").second
  end

  def index_records
    @records = Record.where(user_id: @user.id).includes(:user).order("created_at DESC").page(params[:page]).per(20)
    @ad_2 = Advertisement.where(ad_rate_id: 2).order("RAND()").first
  end

  def index_rules
    @rules = Rule.where(user_id: @user.id).includes(:user).order("created_at DESC").page(params[:page]).per(20)
    @ad_3 = Advertisement.where(ad_rate_id: 3).order("RAND()").first
    @ad_4 = Advertisement.where(ad_rate_id: 4).order("RAND()").first
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_user_id
    @user = User.find(params[:user_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% set_meta_tags title: "ユーザー情報の編集" %>
<div class="breadcrumbs">
  <% breadcrumb :user_edit, @user %>
</div>
<div class="content">
  <div class="container_sign">
    <h1><span>登録情報の変更</span></h1>
    
    <%= form_with model: current_user, local: true do |f|%>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>
      
      <div class="field">
        <%= f.label :name %> <br />
        <%= f.text_field :name, autofocus: true %>
      </div>
    
      <div class="actions">
        <%= f.submit "Update", data: { confirm: "メールアドレスを変更した場合はメールをご確認のうえ認証手続きを進めてください" }%>
      </div>
    <% end %>
    <h2>パスワードの変更に関して</h2>
    <p><b>以下の手順で進めてください</b></p>
    <ul class="number">
      <li>ログアウト</li>
      <li>ログインページを表示</li>
      <li>パスワードの再設定を選択</li>
    </ul>
  </div>
</div>

app/views/users/index_records.html.erb
<% set_meta_tags title: "#{@user.name}さんの取引記録一覧}", description: "#{@user.name}さんの取引記録の一覧ページになります" %>
<div class="breadcrumbs">
  <% breadcrumb :user_records, @user %>
</div>
<section class="content">
  <h1><span><%= @user.name %>さんの取引記録</span></h1>
  <div class="grid">
    <% @records.each_slice(8) do |records| %>
      <% records.each do |record| %>
        <%= render partial: "shared/records", locals: { record: record } %>
      <% end %>
      <div class="ad_2"><%= link_to(image_tag(@ad_2.img_url), @ad_2.af_link)%></div>
    <% end %>
  </div>
  <div class="pagi">
    <%= paginate @records %>
  </div>
</section>

app/views/users/index_rules.html.erb
<% set_meta_tags title: "#{@user.name}さんの取引手法一覧}", description: "#{@user.name}さんの取引手法の一覧ページになります" %>
<div class="breadcrumbs">
  <% breadcrumb :user_rules, @user %>
</div>
<section class="content">
  <h1><span><% @user.name %>さんの取引手法</span></h1>
  <div class="grid_">
    <% @rules.each_slice(8) do |rules| %>
      <% rules.each do |rule| %>
        <%= render partial: "shared/rules", locals: { rule: rule } %>
      <% end %>
      <div class="ad_3"><%= link_to(image_tag(@ad_3.img_url), @ad_3.af_link)%></div>
      <div class="ad_4"><%= link_to(image_tag(@ad_4.img_url), @ad_4.af_link)%></div>
    <% end%>
  </div>
  <div class="space"></div>
  <div class="pagi">
    <%= paginate @rules %>
  </div>
</section>

app/views/users/show.html.erb
<% set_meta_tags title: "#{@name}さんの詳細ページ}", description: "#{@name}さんの取引記録の分析などを詳しく見ることができるページです！獲得pips数の推移、全体の勝率、通貨ペア別の勝率が確認できます！", og:{image: image_url('record_date.png')}, twitter:{image: image_url('record_date.png')} %>
<div class="breadcrumbs">
  <% breadcrumb :user_show, @user %>
</div>  
<section class="content">
  <h1><span><%= @name %>さんのページ</span></h1>
  <div class="ad_5"><%= link_to(image_tag(@ad_5_.img_url), @ad_5_.af_link)%></div>
  <div class="ad_2_show"><%= link_to(image_tag(@ad_2_.img_url), @ad_2_.af_link)%></div>
  <%= render partial: "relationships/relationship_btn", locals: { user: @user } %>
  <div class="follow_reration">
    <div class="btn">
      <p><%= link_to "フォロー : #{@user.followings.count}", "/users/#{ @user.id }/followings" %>
    </div>
    <div class="btn">
      <p> <%= link_to "フォロワー : #{@user.followers.count}", "/users/#{ @user.id }/followers" %>
    </div>
  </div>
  <h2><%= @name %>さんの取引分析</h2>
  <h3>獲得pips数</h3>
  <p><b>全体</b><p>
  <%= column_chart @records_by_user.group(:date).sum(:pips), xtitle: "date", ytitle: "pips" %>
  <p><b>直近1ヶ月</b></p>
  <%= column_chart @records_by_user_month.group(:date).sum(:pips), xtitle: "date", ytitle: "pips" %>
  <div>
  </div>
  <h3>全体勝率</h3>
  <div class="win_lose">
    <div class="blue"></div><p>勝ち</p><p>　/　</p><div class="red"></div><p>負け</p>
  </div>
  <%= pie_chart @records_by_user.group(:issue_id).count, donut: true, legend: false %>
  <p class="profit_factor">PF　:　<%= @all_pf.round(2) %></p>
  <h3>通貨ペア別勝率/PF</h3>
  <p><b>全体</b></p>
  <div class="win_lose">
    <div class="blue"></div><p>勝ち</p><p>　/　</p><div class="red"></div><p>負け</p>
  </div>
  <div class="pair_win_rate">
  <% @pair_cat.each do |pair_cat| %>
    <div class="win_rate">
      <% pair_rate = Record.where(pair_id: pair_cat) %>
      <%= Pair.find(pair_cat).name %>の勝率
      <%= pie_chart pair_rate.group(:issue_id).count, donut: true, legend: false %>
      <% pair_pips = pair_rate.where('pips not like?', '-%').pluck(:pips) %>
      <% pair_pips_ = pair_rate.where('pips like?', '-%').pluck(:pips) %>
      <% @pair_pf = pair_pips.sum/pair_pips_.sum.abs %>
      <p class="profit_factor">PF　:　<%= @pair_pf.round(2) %></p>
    </div>
  <% end %>
  </div>
   <b>直近1ヶ月</b>
  <div class="win_lose">
    <div class="blue"></div><p>勝ち</p><p>　/　</p><div class="red"></div><p>負け</p>
  </div>
  <div class="pair_win_rate">
  <% @pair_cat_month.each do |pair_cat| %>
    <div class="win_rate">
      <% pair_rate = Record.where(pair_id: pair_cat) %>
      <%= Pair.find(pair_cat).name %>の勝率
      <%= pie_chart pair_rate.group(:issue_id).count, donut: true, legend: false %>
      <% pair_pips = pair_rate.where(created_at: @from...@to).where('pips not like?', '-%').pluck(:pips) %>
      <% pair_pips_ = pair_rate.where(created_at: @from...@to).where('pips like?', '-%').pluck(:pips) %>
      <% @pair_pf = pair_pips.sum/pair_pips_.sum.abs %>
      <p class="profit_factor">PF　:　<%= @pair_pf.round(2) %></p>
    </div>
  <% end %>
  </div>
  <div class="ad_5"><%= link_to(image_tag(@ad_5.img_url), @ad_5.af_link)%></div>
  <div class="ad_2_show"><%= link_to(image_tag(@ad_2.img_url), @ad_2.af_link)%></div>
  <h2><%= @name %>さんの取引履歴</h2>
  <div class="grid">
    <% @records.each do |record| %>
      <%= render partial: "shared/records", locals: { record: record } %>
    <% end %>
  </div>
  <%= link_to 'もっと見る', user_index_records_path(@user.id), class: "link_to_user" %>
  <h2><%= @name %>さんの取引手法</h2>
  <div class="grid_">
    <% @rules.each do |rule| %>
      <%= render partial: "shared/rules", locals: { rule: rule } %>
    <% end %>
  </div>
  <div class="space"></div>
  <%= link_to 'もっと見る', user_index_rules_path(@user.id) , class: "link_to_user" %>
  <% if user_signed_in? && current_user.id == @user.id %>
    <h2><%= @name %>さんの専用エリア</h2>
    <div class="btn btn--white btn--radius">
      <%= link_to '編集', edit_user_path(current_user.id), class: 'btn_word' %>
    </div>
  <% end %>
  <div class="ad_5"><%= link_to(image_tag(@ad_5_.img_url), @ad_5_.af_link)%></div>
  <div class="ad_2_show"><%= link_to(image_tag(@ad_2_.img_url), @ad_2_.af_link)%></div>
</section>