config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'static_pages#top'
  get "privacy_policy",to: 'static_pages#privacy_policy'
  get "disclaimer",to: 'static_pages#disclaimer'

  resources :records do
    resources :comment_records
    collection do
      get 'search'
    end
  end

  resources :rules do
    resources :comment_rules
    collection do
      get 'search'
    end
  end

  resources :users, only: [:edit, :update, :show,] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers' 
    get "index_records" => 'users#index_records'
    get "index_rules" => 'users#index_rules'
  end

  post 'like_record/:id' => 'like_records#create', as: 'create_like_record'
  delete 'like_record/:id' => 'like_records#destroy', as: 'destroy_like_record'
  post 'like_rule/:id' => 'like_rules#create', as: 'create_like_rule'
  delete 'like_rule/:id' => 'like_rules#destroy', as: 'destroy_like_rule'

  resources :relationships, only: [:create, :destroy]

  resources :advertisements, only: [:new, :create, :destroy]
end

app/models/record.rb
class Record < ApplicationRecord

  def self.last_week
    to = Date.current.at_end_of_day
    from = to - 1.week
    Record.includes(:user).where(created_at: from...to).order('impressions_count DESC').limit(4)
  end

  is_impressionable counter_cache: true

  with_options presence: true do
    validates :date
    validates :ashi_id
    validates :pair_id
    validates :pips, numericality: true
    validates :entry_basis
    validates :issue_id
    validates :kind_id
    validates :lose_reason_id
    validates :lose_reason_text
  end

  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :ashi_id
    validates :pair_id
    validates :issue_id
    validates :kind_id
    validates :lose_reason_id
  end

  belongs_to :user
  has_many :comment_records, dependent: :destroy
  has_one_attached :image 
  has_many :like_records, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :ashi
  belongs_to :pair
  belongs_to :issue
  belongs_to :lose_reason
  belongs_to :kind
  belongs_to :indi_main
  belongs_to :indi_sub
  belongs_to :order

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_record, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :set_q, only: [:index, :search]
  before_action :set_ad_2, only: [:index, :search, :show]
  before_action :set_record_rank, only: [:index, :search, :show]
  before_action :set_rule_rank, except: [:create, :update, :destroy]

  impressionist actions: [:index, :show]

  def index
    @records = Record.includes(:user).order("created_at DESC").page(params[:page]).per(20)
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to records_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @record.update(record_params)
      redirect_to action: :show
    else
      render action: :edit
    end
  end

  def show
    @comment_record = CommentRecord.new
    @comment_records = @record.comment_records
    @ad_5_ = Advertisement.where(ad_rate_id: 5).order("RAND()").second
    @ad_5__ = Advertisement.where(ad_rate_id: 5).order("RAND()").third
    impressionist(@record, nil, unique: [:session_hash])
  end

  def destroy
    @record.destroy
    redirect_to records_path
  end

  def search
    @results = @q.result.order("created_at DESC").page(params[:page]).per(20)
  end

  private

  def record_params
    params.require(:record).permit(:date, :ashi_id, :pair_id, :kind_id, :entry_rate, :exit_rate, :pips, :entry_basis, :issue_id, :lose_reason_id, :lose_reason_text, :image, :indi_main_id, :indi_sub_id, :order_id).merge(user_id: current_user.id)
  end

  def set_record
    @record = Record.find(params[:id])
  end

  def move_to_index
    unless user_signed_in? && current_user.id == @record.user_id
      redirect_to action: :index
    end
  end

  def set_q
    @q = Record.ransack(params[:q])
  end

  def set_ad_2
    @ad_2_ = Advertisement.where(ad_rate_id: 2).order("RAND()").second
    @ad_2__ = Advertisement.where(ad_rate_id: 2).order("RAND()").third
  end

  def set_record_rank
    @record_ranks = Record.last_week
    @ad_2 = Advertisement.where(ad_rate_id: 2).order("RAND()").first
    @ad_5 = Advertisement.where(ad_rate_id: 5).order("RAND()").first
  end

  def set_rule_rank
    to = Date.current.at_end_of_day
    from = to - 1.week
    @rule_ranks = Rule.includes(:user).where(created_at: from...to).order('impressions_count DESC').limit(4)
  end

end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/edit.html.erb
<% set_meta_tags title: "edit record" %>
<div class="breadcrumbs">
  <% breadcrumb :record_edit, @record %>
</div>
<div class="content">
  <div class="container">
    <h1><span>edit trading record</span></h1>
    <%= render partial: "shared/form_record", locals: { record: @record } %>
  </div>
</div>

app/views/records/index.html.erb
<% set_meta_tags title: 'fxの取引記録一覧', description: '「自分の取引記録が最強の取引教材になるその時まで」。みんなのfx取引記録の一覧が集結！通貨ペア、時間足、トレード種別（スキャルピング、デイトレ...）で検索して参考になる取引を見つけよう！' %>
<div class="breadcrumbs">
  <% breadcrumb :records_index %>
</div>
<section class="content">
  <h1><span>みんなの取引記録</span></h1>
  <div class="container">
    <%= search_form_for @q, url: search_records_path do |f| %>
      <%= f.collection_select :pair_id_eq,Pair.all,:id,:name,include_blank: '通貨ペアで検索' %>
      <%= f.collection_select :ashi_id_eq,Ashi.all,:id,:name,include_blank: '時間足で検索' %>
      <%= f.collection_select :indi_main_id_eq,IndiMain.all,:id,:name,include_blank: 'インジケーターで検索' %>
      <%= f.collection_select :kind_id_eq,Kind.all,:id,:name,include_blank: 'トレード種別で検索' %>
      <%= f.collection_select :issue_id_eq,Issue.all,:id,:name,include_blank: '勝敗で検索' %>
      <%= f.collection_select :lose_reason_id_eq,LoseReason.all,:id,:name,include_blank: '理由で検索' %>
      <%= f.submit '検索' %>
    <% end %>
  </div>

  <div class="grid">
    <% @records.each_slice(8) do |records| %>
      <% records.each do |record| %>
        <%= render partial: "shared/records", locals: { record: record } %>
      <% end %>
      <div class="ad_2"><%= link_to(image_tag(@ad_2.img_url), @ad_2.af_link)%></div>
    <% end %>
  </div>
  <div class="pagi">
    <%= paginate @records %>
  </div>
  <%= render partial: "shared/rank_record", locals: { records: @record_ranks } %>
  <%= render partial: "shared/rank_rule", locals: { rules: @rule_ranks } %>
</section>

app/views/records/new.html.erb
<% set_meta_tags title: "new record" %>
<div class="breadcrumbs">
  <% breadcrumb :record_new, @record %>
</div>
<div class="content">
  <div class="container">
    <h1><span>new record</span></h1>
    <%= render partial: "shared/form_record", locals: { record: @record } %>
  </div>
</div>

app/views/records/search.html.erb
<% set_meta_tags title: 'fxの取引記録一覧', description: 'みんなのfx取引の一覧が集結！通貨ペア、時間足、トレード種別（スキャルピング、デイトレ...）で検索して参考になる取引を見つけよう！' %>
<div class="breadcrumbs">
  <% breadcrumb :record_search, @record %>
</div>
<section class="content">
  <h1><span>以下の条件での検索結果</span></h1>
  <% if @results.length != 0 %>
    <div class="container">
      <%= search_form_for @q, url: search_records_path do |f| %>
        <%= f.collection_select :pair_id_eq,Pair.all,:id,:name,include_blank: '通貨ペアで検索' %>
        <%= f.collection_select :ashi_id_eq,Ashi.all,:id,:name,include_blank: '時間足で検索' %>
        <%= f.collection_select :indi_main_id_eq,IndiMain.all,:id,:name,include_blank: 'インジケーターで検索' %>
        <%= f.collection_select :kind_id_eq,Kind.all,:id,:name,include_blank: 'トレード種別で検索' %>
        <%= f.collection_select :issue_id_eq,Issue.all,:id,:name,include_blank: '勝敗で検索' %>
        <%= f.collection_select :lose_reason_id_eq,LoseReason.all,:id,:name,include_blank: '理由で検索' %>
        <%= f.submit '検索' %>
      <% end %>
    <%= link_to "一覧に戻る", records_path, class: "btn_" %>
    </div>
    
    <div class="grid">
    <% @results.each_slice(8) do |records| %>
      <% records.each do |record| %>
        <%= render partial: "shared/records", locals: { record: record } %>
      <% end %>
      <div class="ad_2"><%= link_to(image_tag(@ad_2.img_url), @ad_2.af_link)%></div>
    <% end %>
    </div>
    <div class="pagi">
      <%= paginate @results %>
    </div>
  <% else %>
    該当する記録はありません
    <%= link_to "一覧に戻る", records_path, class: "btn_" %>
  <% end %>
  <%= render partial: "shared/rank_record", locals: { records: @record_ranks } %>
  <%= render partial: "shared/rank_rule", locals: { rules: @rule_ranks } %>
</section>

app/views/records/show.html.erb
<% if @record.image.attached? %>
  <% set_meta_tags title: "#{@record.pair.name}で#{@record.pips}pips獲得した取引", description: "エントリー根拠：#{@record.entry_basis}", keywords: "fx, #{@record.pair.name}, 取引記録", og:{image: image_url(url_for(@record.image))}, twitter:{image: image_url(url_for(@record.image))} %>
<% else %>
  <% set_meta_tags title: "#{@record.pair.name}で#{@record.pips}pips獲得した取引", description: "エントリー根拠：#{@record.entry_basis}", keywords: "fx, #{@record.pair.name}, 取引記録", og:{image: image_url('sample.jpg')} %>
<% end %>
<div class="breadcrumbs">
  <% breadcrumb :record_show, @record %>
</div>

<section class="content">
  <% if @record.issue.id == 2 %>
    <h1><span><%= @record.pair.name %>で<%= @record.pips %>pips獲得した取引の詳細</span></h1>
  <% else @record.issue.id == 3 %>
    <h1><span><%= @record.date %>の取引記録</span></h1>
  <% end %>
<%#  <div class="move_page">
<%#    <% if request.referer&.include?("/users/") || request.referer&.include?("/index_records.") %>
<%#      <% if @record.previous_record_user.present? %>
<%#        <%= link_to "< PREV", record_path(@record.previous_record_user), class: "btn_word"%>
<%#      <% end %>
<%#      <% if @record.next_record.user.present? %>
<%#        <%= link_to "NEXT >",record_path(@record.next_record_user), class: "btn_word" %>
<%#      <% end %>
<%#    <% elsif request.referer&.include?("/records") %>
<%#      <% if @record.previous_record.present? %>
<%#        <%= link_to "< PREV", record_path(@record.previous_record), class: "btn_word"%>
<%#      <% end %>
<%#      <% if @record.next_record.present? %>
<%#        <%= link_to "NEXT >",record_path(@record.next_record), class: "btn_word" %>
<%#      <% end %>
<%#    <% end %>
<%#  </div>  %>
  <div class="record_content">
    <div class="left_content">
      <h2>取引画像</h2>
      <% if @record.image.attached? %>
        <%= link_to image_tag(@record.image, class:"recorded_img_show") %>
      <% else %>
        <%= link_to image_tag("no_image.jpg", class:"recorded_img_show") %>
      <% end %>
    </div>
    <div class="right_content">
      <h2>取引概要</h2>
      <table>
        <tr>
          <th>取引日</th>
          <td><%= @record.date %></td>
        </tr>
        <tr>
          <th>通貨ペア</th>
          <td><%= @record.pair.name %> </td>
        </tr>
        <tr>
          <th>時間足</th>
          <td><%= @record.ashi.name %> </td>
        </tr>
        <tr>
          <th>トレード種別</th>
          <td><%= @record.kind.name %> </td>
        </tr>
        <% if @record.indi_main != nil %>
          <tr>
            <th>メインインジケーター</th>
            <td><%= @record.indi_main.name %> </td>
          </tr>
        <% end %>
        <% if @record.indi_sub != nil %>
          <tr>
            <th>サブインジケーター</th>
            <td><%= @record.indi_sub.name %> </td>
          </tr>
        <% end %>
        <% if @record.order != nil %>
          <tr>
            <th>注文方式</th>
            <td><%= @record.order.name %> </td>
          </tr>
        <% end %>
        <% if @record.entry_rate != nil %>
          <tr>
            <th>エントリー価格</th>
            <td><%= @record.entry_rate %> </td>
          </tr>
        <% end %>
        <% if @record.exit_rate != nil %>
          <tr>
            <th>決済価格</th>
            <td><%= @record.exit_rate %> </td>
          </tr>
        <% end %>
        <% if @record.issue.id == 2 %>
          <tr>
            <th>利益</th>
            <td><%= @record.pips %>pips</td>
          </tr>
        <% elsif @record.issue.id == 3 %>
          <tr>
            <th>損失</th>
            <td><%= @record.pips %>pips</td>
          </tr>
        <% else %>
          <tr>
            <th>獲得値幅</th>
            <td>記録なし</td>
          </tr>
        <% end %>
        <tr>
          <th>取引結果</th>
          <td><%= @record.lose_reason.name %></td>
        </tr>
        <tr>
          <th>created by</th>
          <td><%= link_to @record.user.name, "/users/#{@record.user_id}" %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="ad_5"><%= link_to(image_tag(@ad_5__.img_url), @ad_5__.af_link)%></div>
  <div class="ad_2_show"><%= link_to(image_tag(@ad_2__.img_url), @ad_2__.af_link)%></div>
  <div class="entry_basis">
    <h2>エントリーした根拠</h2>
    <div class="show_content">
      <%= safe_join(@record.entry_basis.split("\n"),tag(:br)) %>
    </div>
  </div>
  <div class="lose_reason">
    <h2>今回の取引の総括</h2>
    <div class="show_content">
      <%= safe_join(@record.lose_reason_text.split("\n"),tag(:br)) %>
    </div>
  </div>
  <% if user_signed_in? && current_user.id == @record.user_id %>
    <div class="lose_reason">
      <h2>投稿者専用エリア</h2>
      <div class="for_user">
        <div class="btn btn--white btn--radius">
          <%= link_to '編集', edit_record_path(@record.id), class: 'btn_word' %>
        </div>
        <div class="btn btn--white btn--radius">
          <%= link_to '削除', record_path(@record.id), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn_word' %>
        </div>
      </div>
    </div>
  <% end %>
  
<%#  <div class="move_page">
<%#    <% if @record.previous_record.present? %>
<%#      <%= link_to "< PREV", record_path(@record.previous_record), class: "btn_word"%>
<%#    <% end %>
<%#    <% if @record.next_record.present? %>
<%#      <%= link_to "NEXT >",record_path(@record.next_record), class: "btn_word" %>
<%#    <% end %>
<%#  </div> %>
  <%= render partial: "shared/rank_record", locals: { records: @record_ranks } %>
  <h2>コメント</h2>
  <div class="container">
    <div class="likes_buttons_<%= @record.id %>">
      <%= render partial: 'like_records/like', locals: { record: @record } %>
    </div>
    <div>
      <i class="fas fa-eye like-btn"></i>_<%= @record.impressions_count %>
    </div>
    <%= form_with model: [@record, @comment_record],url: record_comment_records_path(@record), local: false do |form| %>
      <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
      <%= form.submit "SEND" %>
    <% end %>
    <div class="comments">
      <h3>＜コメント一覧＞</h3>
      <div id="comments__area">
        <%= render partial: 'comment_records/index', locals: { comments: @comment_records } %>
      </div>
    </div>
  </div>
  <div class="ad_5"><%= link_to(image_tag(@ad_5_.img_url), @ad_5_.af_link)%></div>
  <div class="ad_2_show"><%= link_to(image_tag(@ad_2_.img_url), @ad_2_.af_link)%></div>
  <%= render partial: "shared/rank_rule", locals: { rules: @rule_ranks } %>
</section>