config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'static_pages#top'
  get "privacy_policy",to: 'static_pages#privacy_policy'
  get "disclaimer",to: 'static_pages#disclaimer'

  resources :records do
    resources :comment_records
    collection do
      get 'search'
    end
  end

  resources :rules do
    resources :comment_rules
    collection do
      get 'search'
    end
  end

  resources :users, only: [:edit, :update, :show,] do
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers' 
    get "index_records" => 'users#index_records'
    get "index_rules" => 'users#index_rules'
  end

  post 'like_record/:id' => 'like_records#create', as: 'create_like_record'
  delete 'like_record/:id' => 'like_records#destroy', as: 'destroy_like_record'
  post 'like_rule/:id' => 'like_rules#create', as: 'create_like_rule'
  delete 'like_rule/:id' => 'like_rules#destroy', as: 'destroy_like_rule'

  resources :relationships, only: [:create, :destroy]

  resources :advertisements, only: [:new, :create, :destroy]
end

app/models/rule.rb
class Rule < ApplicationRecord

  def self.last_week
    to = Date.current.at_end_of_day
    from = to - 1.week
    Rule.includes(:user).where(created_at: from...to).order('impressions_count DESC').limit(4)
  end

  is_impressionable counter_cache: true

  with_options presence: true do
    validates :image
    validates :name
    validates :ashi_id
    validates :kind_id
    validates :pair_id
    validates :issue_id
    validates :overview
    validates :overview_content
    validates :entry
    validates :exit
    validates :summary
  end

  with_options numericality: { other_than: 1 ,message: 'を選択してください' } do
    validates :ashi_id
    validates :pair_id
    validates :issue_id
    validates :kind_id
  end

  belongs_to :user
  has_one_attached :image 
  has_many :comment_rules, dependent: :destroy
  has_many :like_rules, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :ashi
  belongs_to :pair
  belongs_to :issue
  belongs_to :kind
  belongs_to :indi_main
  belongs_to :indi_sub

end

app/controllers/rules_controller.rb
class RulesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_rule, only: [:edit, :update, :show, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :set_q, only: [:index, :search]
  before_action :set_ad_3_4, only: [:index, :search]
  before_action :set_rule_rank, except: [:create, :update, :destroy]
  before_action :set_record_rank, except: [:create, :update, :destroy]

  impressionist actions: [:index, :show]

  def index
    @rules = Rule.includes(:user).order("created_at DESC").page(params[:page]).per(20)
  end

  def new
    @rule = Rule.new
  end

  def create
    @rule = Rule.new(rule_params)
    if @rule.save
      redirect_to rules_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @rule.update(rule_params)
      redirect_to action: :show
    else
      render action: :edit
    end
  end

  def destroy
    @rule.destroy
    redirect_to rules_path
  end

  def show
    @comment_rule = CommentRule.new
    @comment_rules = @rule.comment_rules
    @ad_5 = Advertisement.where(ad_rate_id: 5).order("RAND()").first
    @ad_5_ = Advertisement.where(ad_rate_id: 5).order("RAND()").second
    @ad_2 = Advertisement.where(ad_rate_id: 2).order("RAND()").first
    @ad_2_ = Advertisement.where(ad_rate_id: 2).order("RAND()").second
    impressionist(@rule, nil, unique: [:session_hash])
  end

  def search
    @results = @q.result.order("created_at DESC").page(params[:page]).per(20)
  end

  private

  def rule_params
    params.require(:rule).permit(:name, :ashi_id, :kind_id, :pair_id, :entry, :exit, :issue_id, :overview, :overview_content, :summary, :image, :indi_main_id, :indi_sub_id).merge(user_id: current_user.id)
  end

  def set_rule
    @rule = Rule.find(params[:id])
  end

  def move_to_index
    unless user_signed_in? && current_user.id == @rule.user_id
      redirect_to action: :index
    end
  end

  def set_q
    @q = Rule.ransack(params[:q])
  end

  def set_ad_3_4
    @ad_3 = Advertisement.where(ad_rate_id: 3).order("RAND()").first
    @ad_4 = Advertisement.where(ad_rate_id: 4).order("RAND()").first
  end

  def set_rule_rank
    @rule_ranks = Rule.last_week
    @ad_2 = Advertisement.where(ad_rate_id: 2).order("RAND()").first
    @ad_5 = Advertisement.where(ad_rate_id: 5).order("RAND()").first
  end

  def set_record_rank
    to = Date.current.at_end_of_day
    from = to - 1.week
    @record_ranks = Record.includes(:user).where(created_at: from...to).order('impressions_count DESC').limit(4)
  end

end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/edit.html.erb
<% set_meta_tags title: "edit rule" %>
<div class="breadcrumbs">
  <% breadcrumb :rule_edit, @rule %>
</div>
<div class="content">
  <div class="container">
    <h1><span>edit trading method<span></h1>
    <%= render partial: "shared/form_rule", locals: { rule: @rule } %>
  </div>
</div>

app/views/rules/index.html.erb
<% set_meta_tags title: 'fxの取引手法一覧', description: 'みんなのfxの取引手法の一覧が集結！通貨ペア、時間足、トレード種別（スキャルピング、デイトレ...）で検索して参考になる取引手法を見つけよう！', keywords: "fx, 投資, 取引手法" %>
<div class="breadcrumbs">
  <% breadcrumb :rules_index, @rule %>
</div>
<section class="content">
  <h1><span>みんなの取引手法</span></h1>
  <div class="container">
    <%= search_form_for @q, url: search_rules_path do |f| %>
      <%= f.collection_select :pair_id_eq,Pair.all,:id,:name,include_blank: '推奨通貨ペアで検索' %>
      <%= f.collection_select :ashi_id_eq,Ashi.all,:id,:name,include_blank: '推奨時間足で検索' %>
      <%= f.collection_select :indi_main_id_eq,IndiMain.all,:id,:name,include_blank: 'インジケーターで検索' %>
      <%= f.collection_select :kind_id_eq,Kind.all,:id,:name,include_blank: '推奨トレード種別で検索' %>
      <%= f.collection_select :issue_id_eq,Issue.all,:id,:name,include_blank: '勝てるか負けるかで検索' %>
      <%= f.submit '検索' %>
    <% end %>
  </div>
  <div class="grid_">
    <% @rules.each_slice(8) do |rules| %>
      <% rules.each do |rule| %>
        <%= render partial: "shared/rules", locals: { rule: rule } %>
      <% end %>
      <div class="ad_3"><%= link_to(image_tag(@ad_3.img_url), @ad_3.af_link)%></div>
      <div class="ad_4"><%= link_to(image_tag(@ad_4.img_url), @ad_4.af_link)%></div>
    <% end%>
  </div>
  <div class="pagi">
    <%= paginate @rules %>
  </div>
  <%= render partial: "shared/rank_rule", locals: { rules: @rule_ranks } %>
  <%= render partial: "shared/rank_record", locals: { records: @record_ranks } %>
</section>
<div class="space"></div>

app/views/rules/new.html.erb
<% set_meta_tags title: "new rule" %>
<div class="breadcrumbs">
  <% breadcrumb :rule_new, @rule %>
</div>
<div class="content">
  <div class="container">
    <h1><span>new method</span></h1>
    <%= render partial: "shared/form_rule", locals: { rule: @rule } %>
  </div>
</div>

app/views/rules/search.html.erb
<% set_meta_tags title: 'fxの取引手法一覧', description: 'みんなのfxの取引手法の一覧が集結！通貨ペア、時間足、トレード種別（スキャルピング、デイトレ...）で検索して参考になる取引手法を見つけよう！', keywords: "fx, 投資, 取引手法" %>
<div class="breadcrumbs">
  <% breadcrumb :rule_search, @rule %>
</div>
<section class="content">
  <h1><span>以下の条件での検索結果</span></h1>
  <% if @results.length != 0 %>
    <div class="container">
      <%= search_form_for @q, url: search_rules_path do |f| %>
        <%= f.collection_select :pair_id_eq,Pair.all,:id,:name,include_blank: '推奨通貨ペアで検索' %>
        <%= f.collection_select :ashi_id_eq,Ashi.all,:id,:name,include_blank: '推奨時間足で検索' %>
        <%= f.collection_select :indi_main_id_eq,IndiMain.all,:id,:name,include_blank: 'インジケーターで検索' %>
        <%= f.collection_select :kind_id_eq,Kind.all,:id,:name,include_blank: '推奨トレード種別で検索' %>
        <%= f.collection_select :issue_id_eq,Issue.all,:id,:name,include_blank: '勝てるか負けるかで検索' %>
        <%= f.submit '検索' %>
      <% end %>
      <%= link_to "一覧に戻る", rules_path, class: "btn_" %>
    </div>
    <div class="grid_">
      <% @results.each_slice(8) do |rules| %>
        <% rules.each do |rule| %>
          <%= render partial: "shared/rules", locals: { rule: rule } %>
        <% end %>
        <div class="ad_3"><%= link_to(image_tag(@ad_3.img_url), @ad_3.af_link)%></div>
        <div class="ad_4"><%= link_to(image_tag(@ad_4.img_url), @ad_4.af_link)%></div>
      <% end %>
    </div>
    <div class="space"></div>
    <div class="pagi">
      <%= paginate @results %>
    </div>
  <% else %>
    該当する記録はありません
    <%= link_to "一覧に戻る", rules_path, class: "btn_" %>
  <% end %>
  <%= render partial: "shared/rank_rule", locals: { rules: @rule_ranks } %>
  <%= render partial: "shared/rank_record", locals: { records: @record_ranks } %>
</section>

app/views/rules/show.html.erb
<% set_meta_tags title: "#{@rule.name}", description: "#{@rule.entry}", keywords: "fx, #{@rule.pair.name}, 取引手法", og:{image: image_url(url_for(@rule.image))}, twitter:{image: image_url(url_for(@rule.image))} %>
<div class="breadcrumbs">
  <% breadcrumb :rule_show, @rule %>
</div>
<section class="content">
  <h1><span><%= @rule.name %></span></h1>
  
<%#  <div class="move_page">
<%#    <% if @rule.previous_rule.present? %>
<%#      <%= link_to "< PREV", rule_path(@rule.previous_rule), class: "btn_word"%>
<%#    <% end %>
<%#    <% if @rule.next_rule.present? %>
<%#      <%= link_to "NEXT >",rule_path(@rule.next_rule), class: "btn_word" %>
<%#    <% end %>
<%#  </div> %>
  
  <div class="record_content">
    <div class="left_content">
      <h2>取引画像</h2>
      <%= link_to image_tag(@rule.image, class:"recorded_img_show") %>
    </div>
    <div class="right_content">
      <h2>取引概要</h2>
      <table>
        <tr>
          <th>推奨通貨ペア</th>
          <td><%= @rule.pair.name %> </td>
        </tr>
        <tr>
          <th>推奨時間足</th>
          <td><%= @rule.ashi.name %> </td>
        </tr>
        <tr>
          <th>推奨トレード種別</th>
          <td><%= @rule.kind.name %> </td>
        </tr>
        <% if @rule.indi_main != nil %>
          <tr>
            <th>メインインジケーター</th>
            <td><%= @rule.indi_main.name %> </td>
          </tr>
        <% end %>
        <% if @rule.indi_sub != nil %>
          <tr>
            <th>サブインジケーター</th>
            <td><%= @rule.indi_sub.name %> </td>
          </tr>
        <% end %>
        <% if @rule.issue.id == 2 %>
          <tr>
            <th>勝てる？負ける？</th>
            <td>勝てる</td>
          </tr>
        <% else @rule.issue.id == 3 %>
          <tr>
            <th>勝てる？負ける？</th>
            <td>負ける</td>
          </tr>
        <% end %>
        <tr>
          <th>created by</th>
          <td><%= link_to @rule.user.name, "/users/#{@rule.user_id}" %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="ad_5"><%= link_to(image_tag(@ad_5.img_url), @ad_5.af_link)%></div>
  <div class="ad_2_show"><%= link_to(image_tag(@ad_2.img_url), @ad_2.af_link)%></div>
  <div class="entry_basis">
    <h2><%= @rule.overview %></h2>
    <div class="show_content">
      <%= safe_join(@rule.overview_content.split("\n"),tag(:br)) %>
      </div>
  </div>
  <div class="entry_basis">
    <h2>エントリータイミング</h2>
    <div class="show_content">
      <%= safe_join(@rule.entry.split("\n"),tag(:br)) %>
    </div>
  </div>
  <div class="entry_basis">
    <h2>決済タイミング</h2>
    <div class="show_content">
      <%= safe_join(@rule.entry.split("\n"),tag(:br)) %>
    </div>
  </div>
  <div class="lose_reason">
    <h2>今回の取引の総括</h2>
    <div class="show_content">
      <%= safe_join(@rule.exit.split("\n"),tag(:br)) %>
    </div>
  </div>
  <% if user_signed_in? && current_user.id == @rule.user_id %>
    <div class="lose_reason">
      <h2>投稿者専用エリア</h2>
      <div class="for_user">
        <div class="btn btn--white btn--radius">
          <%= link_to '編集', edit_rule_path(@rule.id), class: 'btn_word' %>
        </div>
        <div class="btn btn--white btn--radius">
        <%= link_to '削除', rule_path(@rule.id), method: :delete, data: { confirm: "削除しますか？" }, class: 'btn_word'%>
        </div>
      </div>
    </div>
  <% end %>
  
<%#  <div class="move_page">
<%#    <% if @rule.previous_rule.present? %>
<%#      <%= link_to "< PREV", rule_path(@rule.previous_rule), class: "btn_word"%>
<%#    <% end %>
<%#    <% if @rule.next_rule.present? %>
<%#      <%= link_to "NEXT >",rule_path(@rule.next_rule), class: "btn_word" %>
<%#    <% end %>
<%#  </div> %>
  <%= render partial: "shared/rank_rule", locals: { rules: @rule_ranks } %>
  <h2>コメント</h2>
  <div class="container">
    <div class="likes_buttons_<%= @rule.id %>">
      <%= render partial: 'like_rules/like', locals: {rule: @rule} %>
    </div>
    <div>
      <i class="fas fa-eye like-btn"></i>_<%= @rule.impressions_count %>
    </div>
    <%= form_with model: [@rule, @comment_rule], url: rule_comment_rules_path(@rule), local: false do |form| %>
      <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
      <%= form.submit "SEND" %>
    <% end %>
    <div class="comments">
      <h3>＜コメント一覧＞</h3>
      <div id="comments_area">
        <%= render partial: 'comment_rules/index', locals: { comments: @comment_rules } %>
      </div>
    </div>
  </div>
  <div class="ad_5"><%= link_to(image_tag(@ad_5_.img_url), @ad_5_.af_link)%></div>
  <div class="ad_2_show"><%= link_to(image_tag(@ad_2_.img_url), @ad_2_.af_link)%></div>
  <%= render partial: "shared/rank_record", locals: { records: @record_ranks } %>
</section>